#ifndef USER_H
#define USER_H
#include <string>

class User {
private:
    std::string username;
    std::string password; // Luu m?t kh?u bam

    bool IsAutoGenerated;

public:
    User(const std::string& uname, const std::string& pwd);
    std::string getUsername() const;
    std::string getPassword() const;
};

// Hàm bam m?t kh?u
std::string hashPassword(const std::string& password);

// Hàm dang ký tài kho?n
bool registerUser(const std::string& username, const std::string& password);

// Ham dang nhap
bool loginUser(const std::string& username, const std::string& password);

#endif
