#ifndef USER_H
#define USER_H
#include <string>
#include <vector>

class User {
private:
    std::string username;
    std::string password; // Luu m?t kh?u bam
	bool isAutoGenerated; 
public:
    User(const std::string& uname, const std::string& pwd, bool isAuto);
    std::string getUsername() const;
    std::string getPassword() const;
    bool IsAuto();
};

// Hàm bam m?t kh?u
std::string hashPassword(const std::string& password);
// Auto tao mat khau
std::string AutoGenerated();
// Hàm dang ký tài kho?n
bool registerUser(const std::string& username, const std::string& password, bool isAuto);
bool loginUser(const std::string& username, const std::string& password);
bool ChangePassword(const std::string& username, const std::string& Newpassword);


#endif
