#include "../include/ui.h"
#include "../include/user.h"
#include <cstdlib>
using namespace std;
int main() {
    while (true) {
        showMenu();
        char choice = getMenuChoice();
        system("cls");

        if (choice == '1') {		//LOGIN
        while (true) {
            showLoginScreen();
            string username = getInput("Please enter your username: ");
            string password = getInput("Please enter your password: ");
            if (loginUser(username, password)) {
                showMessage(">> SUCCESSFULLY LOGIN <<");  
				break;  
				system("cls");
				/*
					DEVELOPING....
					MOVE TO THE MAIN TRANSACTION MENU IN HERE;
				*/
			} else {
				system("cls");
                showMessage(">> LOGIN FAILED. Please try again.\n");
            }
        }
        
        } else if (choice == '2') {	//REGISTER
        	while (true) {
        		showRegisterScreen();
	            string username = getInput("Please enter your username: ");
	            string password = getInput("Please enter your password: ");
	            bool check = false;
	            if (registerUser(username, password, check)) {
	                showMessage(">>> SUCCESSFULLY CREATE ACCOUNT <<<");
	                break; 
	            } else {
	            	system("cls");
	                showMessage("Invalid input or username exists!\n");
	            }
			}
			
        } else if (choice == '3'){	//REGISTER FOR MANGER
        	showRegisterScreenForMnger();
        	while (true) {
        		string adminPassword = getInput("Enter admin password: ");
        		if (adminPassword == "admin123") {
        			system("cls");
        			break;
				}
        		else {
        			system("cls");
					showMessage("WRONG PASSWORD\n");
				}
			}
        	string username = getInput("Please enter your username: ");
        	string autoPassword = AutoGenerated();
        	bool check = true;
        	if (registerUser(username, autoPassword, check)) {
        		showMessage("User created! Auto-generated password: " + autoPassword);
        		break;
            } else {
                showMessage("Invalid input or username exists!\n");
            }
		}
    }
    return 0;
}
